// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oreupylavvhqoowntixj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZXVweWxhdnZocW9vd250aXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDU0MDcsImV4cCI6MjA1ODc4MTQwN30.3ElzOnG4xClIZ60LvCDZoYe8E-o42bTpjSc1XTqaCA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);